#
# This is sample docker file for use in a prod environment
#
# NOTE:
# You will need to create the redis-data volumes:
# docker volume create --name=redis-data
#
# NOTE: if you want to run postgres in a container have a look at the staging compose file
# you will need to set the links for web and sidekiq accordingling and also set up
# an external volume for postgres data
#
# docker volume create --name=pgdata
#

version: "3.7"

volumes:
  redis-data:
    external: true
  pgdata:
    external: true
services:
  redis:
    image: redis:435993df2c8d
    restart: always
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:db2247d3e23c
    restart: always
    env_file:
      # NOTE: this will need to reflect local system
      - "/opt/plano/etc/planorama.env"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    command: "/opt/planorama/script/planorama_start.sh"
    # planorama:latest for latest release (tagged)
    # planorama:main for latest build of main branch
    image: planorama-copernicon:0.1.0
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      # NOTE: this will need to reflect local system
      - /var/log/planorama/web:/opt/planorama/log
      - type: tmpfs
        target: /app/tmp
    environment:
      - PGID=1005
      - PUID=1001
      - RAILS_ENV=production
      - NODE_ENV=production
    env_file:
      # NOTE: this will need to reflect local system
      - "/opt/plano/etc/planorama.env"
    depends_on:
      - redis
    links:
      - redis
    restart: always

  planorama-sidekiq:
    command: "/opt/planorama/script/planorama_sidekiq.sh"
    # See above note re which image to use
    image: planorama-copernicon:0.1.0
    volumes:
      # NOTE: this will need to reflect local system
      - /var/log/planorama/sidekiq:/opt/planorama/log
      - type: tmpfs
        target: /app/tmp
    environment:
      - PGID=1005
      - PUID=1001
      - RAILS_ENV=production
      - NODE_ENV=production
    env_file:
      # NOTE: this will need to reflect local system
      - "/opt/plano/etc/planorama.env"
    depends_on:
      - redis
    links:
      - redis
    restart: always
